### ISSUE TITLE
master fails to build on old gcc (below version 9)

### ISSUE THREAD

**Issue by 0xkag** [Tarsnap/tarsnap#473] opened 2021-02-21 18:36 UTC
Perhaps this is intentional?  But in any case, `master` at d067c043d01e doesn't build on i686.  It fails with the following error:

```
libcperciva/crypto/crypto_aesctr_aesni.c: In function ‘crypto_aesctr_aesni_stream_wholeblocks’:
libcperciva/crypto/crypto_aesctr_aesni.c:47:13: warning: implicit declaration of function ‘_mm_loadu_si64’ [-Wimplicit-function-declaration]
  nonce_be = _mm_loadu_si64(stream->pblk);
             ^~~~~~~~~~~~~~
libcperciva/crypto/crypto_aesctr_aesni.c:47:11: error: incompatible types when assigning to type ‘__m128i {aka __vector(2) long long int}’ from type ‘int’
  nonce_be = _mm_loadu_si64(stream->pblk);
           ^
libcperciva/crypto/crypto_aesctr_aesni.c:63:10: error: incompatible types when assigning to type ‘__m128i {aka __vector(2) long long int}’ from type ‘int’
   bufsse = _mm_loadu_si64(block_counter_be_arr);
          ^
```

I did not bother bisecting to determine when it was introduced.

**Comment by 0xkag** [comment] 2021-02-21 18:40
A quick git blame shows changes in c0046fa6 and 27837300 on these lines made on 2021-01-19 by @gperciva.

**Comment by gperciva** [comment] 2021-02-21 18:43
Huh, that shouldn't be enabled unless your CPU supports AESNI.  Could you please paste the contents of your `cpusupport-config.h`?  It should be in the main build directory (probably the top level of the source tree).

**Comment by gperciva** [comment] 2021-02-21 18:45
Never mind, I've reproduce it inside virtualbox.  I'll have a fix soon.

**Comment by gperciva** [comment] 2021-02-21 19:21
Looks like a compiler thing:
- gcc: `_mm_loadu_si64` missing https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78782.  It was added to master in 2019-03-08, for gcc-9.
- clang: [X86] add `_mm_loadu_si64` https://reviews.llvm.org/D21504.  That was 2016-06-19.

On my debian buster system, it works with clang-6 and clang-7 (the available version of clang), but not an version of gcc that's in the default package tree.  So a temporary fix might be to try

    CC=clang make

I'm working on a fix for old gcc.

**Comment by gperciva** [comment] 2021-02-21 19:25
Ah, on that note, for the curious: I can reproduce this on modern freebsd amd64, via
```
CC=gcc8 make
```

**Comment by gperciva** [comment] 2021-02-24 01:32
I believe that this was fixed in #474.

**Comment by cperciva** [comment] 2021-03-20 03:29
@0xkag Can you confirm that this is now working for you?

**Comment by 0xkag** [comment] 2021-04-03 16:06
@gperciva, @cperciva, `master` builds for me now:

```shell
% uname -a
Linux <redacted> 5.10.13-x86-linode161 #1 SMP Thu Feb 4 13:51:28 EST 2021 i686 GNU/Linux
```
```shell
% tarsnap --version
tarsnap 1.0.39-head
```
```shell
% git rev-parse HEAD
b27038c31906c0c8a7426d1a50d0d04e9342d929
```

**Comment by gperciva** [comment] 2021-04-03 17:30
Thanks, @0xkag!

**Closed by gperciva** 2021-04-03 17:30 UTC
